MODEL_2D:
  TYPE: "UNetResNet34"
  NUM_CLASSES: 6
MODEL_3D:
  TYPE: "SCN"
  NUM_CLASSES: 6
DATASET_SOURCE:
  TYPE: "SemanticKITTISCN"
  TRAIN: ("train_labeled",)
  SemanticKITTISCN:
    preprocess_dir: "/datasets_local/datasets_mjaritz/semantic_kitti_preprocess/preprocess"
    semantic_kitti_dir: "/datasets_local/datasets_mjaritz/semantic_kitti_preprocess"
    merge_classes_style: "VirtualKITTI"
DATASET_TARGET:
  TYPE: "SemanticKITTISCN"
  VAL: ("val",)
  TEST: ("test",)
  SemanticKITTISCN:
    preprocess_dir: "/datasets_local/datasets_mjaritz/semantic_kitti_preprocess/preprocess"
    semantic_kitti_dir: "/datasets_local/datasets_mjaritz/semantic_kitti_preprocess"
    merge_classes_style: "VirtualKITTI"
DATALOADER:
  NUM_WORKERS: 4
OPTIMIZER:
  TYPE: "Adam"
  BASE_LR: 0.001
SCHEDULER:
  TYPE: "MultiStepLR"
  MultiStepLR:
    gamma: 0.1
    milestones: (25000, 28000)
  MAX_ITERATION: 30000
TRAIN:
  BATCH_SIZE: 8
  SUMMARY_PERIOD: 50
  CHECKPOINT_PERIOD: 2000
  CLASS_WEIGHTS: [1.0364813, 1.27681796, 1., 1.62334721, 3.37626955, 1.46096341]  # SemanticKITTI train_labeled
VAL:
  BATCH_SIZE: 8
  PERIOD: 2000
#OUTPUT_DIR: "path/to/output/directory/@"  #  @ will be replaced with config path, e.g. nuscenes/usa_singapore/xmuda